src/song_life/album_app/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from album_app import views




app_name = "album_name"

urlpatterns = [
    path("list/", views.AlbumListView.as_view(), name="album_list"),
    path("details/<int:pk>", views.AlbumDetailView.as_view(), name="album_details"),
    path("create/", views.AlbumCreateView.as_view(), name="album_create"),
    path("update/<int:pk>", views.AlbumUpdateView.as_view(), name="album_update"),
    path("delete/<int:pk>", views.AlbumDeleteView.as_view(), name="album_delete"),

    # Song Create, Edit, and Delete
    path("create/<int:pk>/songs", views.SongCreateView.as_view(), name="song_create"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/song_life/song_life/urls.py
from django.contrib import admin
from django.urls import path, include
from album_app import views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("albums/", include("album_app.urls", namespace="album_app"),),
    path("user/", include("user_app.urls", namespace="user_app"),),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/song_life/user_app/urls.py
from django.urls import path
from user_app import views


app_name="user_app"

urlpatterns = [
    path("", views.index, name="user_index"),
    path("register/", views.user_registration, name="user_register"),
    path("login/", views.user_login, name="user_login"),
    path("logout/", views.user_logout, name="user_logout"),
]

src/song_life/album_app/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.urls import reverse
# Create your models here.


#SONG FILEPATH




class Album(models.Model):
    BANGLA = "BAN"
    ROCK = "ROC"
    POP = "POP"
    FOLK = "FOK"
    SOFT = "SOF"
    METAL = "MTAL"
    HARDROCK = "HRK"

    TAGS_CHOICES = [
        (BANGLA, "Bangla"),
        (ROCK, "Rock"),
        (POP, "Pop"),
        (FOLK, "Folk"),
        (SOFT, "Soft"),
        (METAL, "Metal"),
        (HARDROCK, "Hard Rock"),
    ]

    album_name   = models.CharField(max_length=264)
    album_author = models.CharField(max_length=264)
    album_logo   = models.ImageField(upload_to="album-logo")
    album_tags   = MultiSelectField(max_length  = 4*3,
                                    max_choices = 3,
                                    choices     = TAGS_CHOICES,
                                    default     = BANGLA,
                                  )


    def is_upperclass(self):
        return self.album_tags in {self.BANGLA, self.SOFT}


    def __str__(self):
        return self.album_name


    def get_absolute_url(self):
        return reverse("album_app:album_list", kwargs={"pk":self.pk})


# ********************** Song Folder ************************ #
def song_uplopad_path(instance, filename):
    album_name = instance.album.album_name
    return f"album_{album_name}/song/{filename}"

# ********************** Song Folder ************************ #

class Song(models.Model):
    album   = models.ForeignKey(Album,
                            on_delete    = models.CASCADE,
                            related_name ="songs")
    song_title    = models.CharField(max_length=264)
    song_file     = models.FileField(upload_to=song_uplopad_path, blank=False)
    song_duration = models.DecimalField(max_digits=3, decimal_places=2)
    song_favorite = models.BooleanField(default=False)
    song_like     = models.PositiveIntegerField(default=0)


    def __str__(self):
        return self.song_title

src/song_life/user_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    user_profile_pic = models.ImageField(upload_to="user-profile", blank=True)

    def __str__(self):
        return self.user.username

src/song_life/user_app/forms.py
from django import forms
from django.contrib.auth.models import User
from user_app import models


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ("first_name", "last_name", "username", "password")


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = models.UserProfileInfo
        fields = ("user_profile_pic",)

src/song_life/album_app/views.py
from django.shortcuts import render
from album_app import models
from django.urls import reverse_lazy
from django.views.generic import (View,
                                  TemplateView,
                                  ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView,
                                  )
# Create your views here.


class IndexView(TemplateView):
    template_name = "index.html"


class AlbumListView(ListView):
    model = models.Album
    context_object_name = "album_list"
    template_name = "album_app/album_list.html"


class AlbumDetailView(DetailView):
    model = models.Album
    pk = "id"
    context_object_name = "album_details"
    template_name = "album_app/album_details.html"


class AlbumCreateView(CreateView):
    model = models.Album
    fields = ("album_name", "album_author", "album_logo", "album_tags")
    pk = "id"

class AlbumUpdateView(UpdateView):
    model = models.Album
    fields = ("album_name", "album_author", "album_logo", "album_tags")



class AlbumDeleteView(DeleteView):
    model = models.Album
    success_url = reverse_lazy("album_app:album_list")


class SongCreateView(CreateView):
    mdoel = models.Song
    fields = ("song_title", "song_duration", )

src/song_life/user_app/views.py
from django.shortcuts import render
from user_app import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    return render(request,"index.html",{})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("user_app:user_index"))


def user_registration(request):
    print("******** User Registration")
    user_form = forms.UserForm()
    user_profile_form = forms.UserProfileInfoForm()

    if request.method == "POST":
        print("**************POST")
        user_form = forms.UserForm(request.POST)
        user_profile_form = forms.UserProfileInfoForm(request.POST)
        print("**********FORM: "+str(user_form))

        if user_form.is_valid() and user_profile_form.is_valid():
            print("******************* IS_VALID")
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = user_profile_form.save(commit=False)
            profile.user = user

            if "user-profile" in request.FILES:
                profile.user_profile_pic = request.FIELS["user-profile"]

            profile.save()
            print("Going to Redirect!!!")
            return HttpResponseRedirect(reverse("user_app:user_index"))

    context_dict = {
        "user_form":user_form,
        "profile_form":user_profile_form,
    }
    return render(request,"user_app/user_register.html",context_dict)




def user_login(request):

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user =authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse("user_app:user_index"))

            else:
                return HttpResponse("Account is not active")

        else:
            print("Someone try to get access with wrong information")
            print("Username: {} and Password: {}".format(username, password))
            return HttpResponse("Email or Password is not correct")
    return render(request, "user_app/user_login.html",{})

src/song_life/album_app/templates/album_app/album_app_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Song Life</title>
        {% include "style/font_family.html" %}
        {% include "css.html" %}
    </head>
    <body>
        {% include "album_app/album_navbar.html" %}

        <div class="container">
            {% block content_body %}
            {% endblock %}
        </div>
        <!-- ******************* Start jQuery File Link ******************** -->
        <script type="text/javascript" href="{% static "jQuery/myscript.js"%}">

        </script>

        <!-- ******************* End jQuery File Link ******************** -->


    {% include "style/js.html" %}

    </body>
</html>

src/song_life/album_app/templates/album_app/album_confirm_delete.html
{% extends "album_app/album_app_base.html" %}

{% block content_body %}
    <h2 class="text-white">Are you sure to delete {{album.album_name}}?</h2>
    <form class="text-white" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a class="btn btn-info" href="{% url "album_app:album_details" pk=album.pk %}">Cancel</a>
    </form>
{% endblock %}

src/song_life/album_app/templates/album_app/album_details.html
{% extends "album_app/album_app_base.html" %}
{% load static %}

{% block content_body %}
<div class="jumbotron row">

    <!-- ***************** Album Details  ***************** -->
    <div class="col-lg-10">

        {% if album_details.album_logo %}
            <img class="rounded float-left" style="height:250px; width:300px;" src="{{ album_details.album_logo.url }}" alt=""/>
        {% else %}
            <h2>Image Not Found!</h2>
        {% endif %}

        <h2>{{album_details}}</h2>
        <h4>Author: {{album_details.album_author}}</h4>
    </div>

    {% if user.is_authenticated%}
    <!--***********  Edit & Delete Button  *************** -->
    <div class="col-lg-2">
        <a class="btn btn-info" href="{% url "album_app:album_update" pk=album_details.pk %}">Edit</a>
        <a class="btn btn-danger" href="{% url "album_app:album_delete" pk=album_details.pk %}">Delete</a>
    </div>
    {% endif %}

</div>
<br>


<!-- *********** Song List ************ -->
<div class="container-fluid">
    <h2>List of all songs
    {% if user.is_authenticated %}
    <a href="#" id="song_add_btn" class="btn btn-light "> <img src="{% static "icon/song_add_icon.png" %}" alt=""  height="16px" width="16px"> </a>
    <!-- Icon Owner: <a href="http://www.onlinewebfonts.com">oNline Web Fonts</a> -->
    <div id="">
        <h4>Add Song</h4>
        <form id="song_add_form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ album_details.songs.as_p }}
            <input type="submit" class="btn btn-success" value="Add Song">

        </form>
    </div>

    {% endif %}
    </h2>

    <ol>
        {% for song in album_details.songs.all %}
        <li>{{song.song_title}} - {{song.song_duration}} <br>
            <small>{{song.author}}</small></li>
        {% endfor %}
    </ol>
</div>


{% endblock %}

src/song_life/album_app/templates/album_app/album_form.html
{% extends "album_app/album_app_base.html" %}

{% block content_body %}

    <div class="text-white">

    </div>

    {% if user.is_authenticated %}
        <h1 class="text-white">
            {% if form.instance.pk %}
                Edit your album
            {% else %}
                Create your new album
            {% endif %}
        </h1>

        <form class="text-white" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}

            {% if form.instance.pk %}
                <input type="submit" class="btn btn-success" value="Save">
                <a class="btn btn-info" href="{% url "album_app:album_details" pk=form.instance.pk %}">Cancel</a>
            {% else %}
                <input type="submit" class="btn btn-success" value="Create">
                <a class="btn btn-info" href="{% url "album_app:album_list" %}">Cancel</a>
            {% endif %}

        </form>

    {% else %}
        <h1 class="text-white">This page is not available!!!</h1>
    {% endif %}


{% endblock %}

src/song_life/album_app/templates/album_app/album_list.html
{% extends "album_app/album_app_base.html" %}
{% load static %}

{% block content_body %}
        <br>
        {% if album_list %}
        <div class="row">
            <div class="card-deck">


            {% for album in  album_list %}
                <div class="card col-lg-2" style=" width: 16rem;">
                <a class="btn btn-light " href="{% url "album_app:album_details" pk=album.id %}">
                    <img class="card-img-top" src="{{album.album_logo.url}}" alt="Image Not Found!">

                    <div class="card-body">
                        <p class="card-title">{{ album.album_name }}</p>
                    </div>

                </a>
                </div>
            {% endfor %}
            </div>
        </div>
        {% else %}
            <h1>No Album found!</h1>
        {% endif %}

{% endblock %}

src/song_life/album_app/templates/album_app/album_navbar.html
{% load static %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" style="font-family: 'Piedra', cursive;" href="{% url "index" %}">Song Life</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "index" %}">Home <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "album_app:album_list" %}">Album <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" href="#">About <span class="sr-only">(current)</span></a>
                    </li>
                </ul>


                <ul class="navbar-nav justify-content-end ">
                        {% if user.is_authenticated %}
                        <!-- Create an album -->
                        <li class=" song-create-icon nav-item active">
                            <i>
                            <a href="{% url "album_app:album_create" %}">
                                <svg width="2em" height="1.5em" viewBox="0 0 16 16" class="bi bi-file-music" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M4 1h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H4z"/>
                                    <path d="M9 11.5c0 .828-.895 1.5-2 1.5s-2-.672-2-1.5.895-1.5 2-1.5 2 .672 2 1.5z"/>
                                    <path fill-rule="evenodd" d="M9 5v6.5H8V5h1z"/>
                                    <path d="M8 4.754a1 1 0 0 1 .725-.961l1.5-.429a1 1 0 0 1 1.275.962V6L8 7V4.754z"/>
                                </svg>
                            </a>
                            </i>
                        </li>


                        <li class="nav-item active">
                            <a class="nav-link" href="{% url "user_app:user_logout" %}">Logout <span class="sr-only">(current)</span></a>
                        </li>

                        {% else %}

                        <li class="nav-item active">
                            <a class="nav-link" href="{% url "user_app:user_register"%}">Registration <span class="sr-only">(current)</span></a>
                        </li>

                        <li class="nav-item active">
                            <a class="nav-link" href="{% url "user_app:user_login" %}">Login <span class="sr-only">(current)</span></a>
                        </li>
                        {% endif %}
                </ul>


            </div>
        </nav>

src/song_life/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Song Life</title>

        {% include "style/font_family.html" %}
        {% include "style/css.html" %}

    </head>
    <body>
        {% include "navbar.html" %}

        <div class="container">
            {% block content_body %}
            {% endblock %}
        </div>

        <!-- ******************* Start jQuery File Link ******************** -->
        <script type="text/javascript" href="{% static "jQuery/myscript.js"%}">

        </script>

        <!-- ******************* End jQuery File Link ******************** -->

        {% include "style/js.html" %}
    </body>
</html>

src/song_life/templates/css.html
{% load static %}

<!-- ******************* Start CSS File Link ******************** -->
<link rel="stylesheet" href="{% static "bootstrap-css/bootstrap.min.css" %}">
<link rel="stylesheet" href="{% static "bootstrap-css/bootstrap.css" %}">
<link rel="stylesheet" href="{% static "bootstrap-css/bootstrap-grid.css" %}">
<link rel="stylesheet" href="{% static "bootstrap-css/bootstrap-grid.min.css" %}">
<link rel="stylesheet" href="{% static "bootstrap-css/bootstrap-reboot.css" %}">
<link rel="stylesheet" href="{% static "bootstrap-css/bootstrap-reboot.min.css" %}">
<link rel="stylesheet" href="{% static "css/mystyle.css" %}">
<!-- ******************* End CSS File Link ******************** -->

src/song_life/templates/font_family.html
{% load static%}

<!-- ******************* Start Font Family ******************** -->
<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Piedra&display=swap" rel="stylesheet">
<!-- ******************* End Font Family ******************** -->

src/song_life/templates/index.html
{% extends "base.html" %}

{% block content_body %}
    <div class="jumbotron">
        <h1 style="font-family: 'Permanent Marker', cursive;">I can't explain it, but I'll find a song that can...</h1>
    </div>
{% endblock %}

src/song_life/templates/navbar.html
{%load static %}

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" style="font-family: 'Piedra', cursive;" href="{% url "index" %}">Song Life</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "index" %}">Home <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "album_app:album_list" %}">Album <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "admin:index"%}">About <span class="sr-only">(current)</span></a>
                    </li>
                </ul>


                <ul class="navbar-nav justify-content-end ">
                        {% if user.is_authenticated %}
                        <!-- Create an album -->
                        <li class=" song-create-icon nav-item">
                            <i>
                            <a href="{% url "album_app:album_create" %}">
                                <svg width="2em" height="1.5em" viewBox="0 0 16 16" class=" bi bi-file-music" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M4 1h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H4z"/>
                                    <path d="M9 11.5c0 .828-.895 1.5-2 1.5s-2-.672-2-1.5.895-1.5 2-1.5 2 .672 2 1.5z"/>
                                    <path fill-rule="evenodd" d="M9 5v6.5H8V5h1z"/>
                                    <path d="M8 4.754a1 1 0 0 1 .725-.961l1.5-.429a1 1 0 0 1 1.275.962V6L8 7V4.754z"/>
                                </svg>
                            </a>
                            </i>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" href="{% url "user_app:user_logout" %}">Logout <span class="sr-only">(current)</span></a>
                        </li>

                        {% else %}

                        <li class="nav-item active">
                            <a class="nav-link" href="{% url "user_app:user_register"%}">Registration <span class="sr-only">(current)</span></a>
                        </li>

                        <li class="nav-item active">
                            <a class="nav-link" href="{% url "user_app:user_login" %}">Login <span class="sr-only">(current)</span></a>
                        </li>
                        {% endif %}
                </ul>


            </div>
        </nav>

src/song_life/templates/style/css.html
{% load static %}

<!-- ******************* Start CSS File Link ******************** -->
<link rel="stylesheet" href="{% static "bootstrap-css/bootstrap.min.css" %}">
<link rel="stylesheet" href="{% static "bootstrap-css/bootstrap.css" %}">
<link rel="stylesheet" href="{% static "bootstrap-css/bootstrap-grid.css" %}">
<link rel="stylesheet" href="{% static "bootstrap-css/bootstrap-grid.min.css" %}">
<link rel="stylesheet" href="{% static "bootstrap-css/bootstrap-reboot.css" %}">
<link rel="stylesheet" href="{% static "bootstrap-css/bootstrap-reboot.min.css" %}">
<link rel="stylesheet" href="{% static "css/mystyle.css" %}">
<!-- ******************* End CSS File Link ******************** -->

src/song_life/templates/style/font_family.html
{% load static%}

<!-- ******************* Start Font Family ******************** -->
<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Piedra&display=swap" rel="stylesheet">
<!-- ******************* End Font Family ******************** -->

src/song_life/templates/style/js.html
{% load static %}

<!-- ******************* Start jQuery CDN Link ******************** -->
 <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<!-- ******************* End jQuery CDN Link ******************** -->

src/song_life/user_app/templates/user_app/user_login.html
{% extends "user_app/user_register.html" %}

{% block content_body %}
<div class="text-white col-lg-6">
    <br>
    <h1>Log In!</h1>
    <form class="" action="{% url "user_app:user_login" %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input class="form-control" type="text" name="username" placeholder="Username"><br>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input class="form-control" type="password" name="password" placeholder="Password"><br>
        </div>

        <input type="submit" class="btn btn-primary" value="Login">
    </form>
</div>

{% endblock %}

src/song_life/user_app/templates/user_app/user_register.html
{% extends "base.html" %}

{% block content_body %}
<br>
<div class="text-white col-lg-6">
    <h1>Registration Form</h1>
    <form action="{% url "user_app:user_register" %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            <label for="">First Name</label>
            <input class="form-control" type="{{user_form.first_name}}" value="">
        </div>

        <div class="form-group">
            <label for="">Last Name</label>
            <input class="form-control" type="{{user_form.last_name}}" value="" >
        </div>

        <div class="form-group">
            <label for="">Username</label>
            <input class="form-control" type="{{user_form.username}}" value="" >
        </div>

        <div class="form-group">
            <label for="">Email</label>
            <input class="form-control" type="{{user_form.email}}" value="" >
        </div>

        <div class="form-group">
            <label for="">Password</label>
            <input class="form-control" type="{{user_form.password}}" value="">
        </div>

        <div class="form-group">
            <label for="">Profile Picture</label>
            <input class="form-control-file" type="{{profile_form.user_profile_pic}}" value="" >
        </div>



        <input type="submit" class="btn btn-primary" value="Sign Up">
    </form>
</div>

{% endblock %}

<!--

<tr><th><label for="id_first_name">First name:</label></th>
<td><input type="text" name="first_name"
    maxlength="30" id="id_first_name"></td></tr>

<tr><th><label for="id_last_name">Last name:</label></th>
<td><input type="text" name="last_name" maxlength="150"
    id="id_last_name"></td></tr>

<tr><th><label for="id_username">Username:</label></th>
<td><ul class="errorlist"><li>This field is required.</li></ul>
<input type="text" name="username" maxlength="150"
required id="id_username"><br><span class="helptext">
Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
</span></td></tr>


<tr><th><label for="id_password">Password:</label></th>
<td><ul class="errorlist"><li>This field is required.</li></ul>
<input type="password" name="password" required id="id_password">
</td></tr>
-->